# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# --------------------------------- Required --------------------------------- #
# V2 or V1
version: 2

# ---------------------- Build documentation with Sphinx --------------------- #

sphinx:
    configuration: ./conf.py

# ----------- Optionally set the version of Python and requirements ---------- #

python:
    version: 3.8
    install:
        - requirements: ./requirements.txt

# ------- Optionally build your docs in additional formats such as PDF ------- #

formats: []
